services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_subscription_api
    ports:
      - '5438:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      target: production
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/github_subscription_api?schema=public

  test:
    build:
      context: .
      target: test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.test
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/github_subscription_api?schema=public
    profiles:
      - test

volumes:
  pgdata:
